version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn app:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=OPENAI_API_KEY